trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@1
    inputs:
      versionSpec: '20.x'
    displayName: '1. Node.js Environment Setup'

  - script: |
      npm ci
    displayName: '2. Node Modules Install'

  - script: |
      npx playwright install --with-deps
    displayName: '3. Playwright Browsers Download'

  - script: |
      npx playwright test
    displayName: '4. Run Automated Test Cases'